### ISSUE TITLE
Increase character limit for facebook pages - some do not have the usual facebook.com/name type

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleServer#32]
e.g. https://www.facebook.com/pages/Fitness-First-Liverpool-St-Station/170689182941527?fref=ts

**Comment by krzd** [comment]
No need. That is a search engine friendly URL. You can also just use the URL in the form facebook.com/USERNAME or facebook.com/ID.
As the ID in this case is 170689182941527, the following URL works just as well: https://www.facebook.com/170689182941527.
